chore: add black linter

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -35,3 +35,19 @@ jobs:
       - name: Test with pytest
         run: |
           python -m pytest
+
+  lint:
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install linters
+        # black is synced with the .pre-commit-hooks version
+        run: |
+          python -m pip install --upgrade pip
+          pip install black==23.11.0
+
+      - name: Run black
+        if: success() || failure() # still run black if above checks fails
+        run: |
+          black --check --verbose .
